### ISSUE TITLE
GLPlot display creation not working in 0.3.7

### ISSUE THREAD

**Issue by dlfivefifty** [SimonDanisch/GLPlot.jl#27]
julia> using GLPlot,GLAbstraction

julia> createdisplay(;async=false, w=500, h=500, eyeposition=Vec3(1,1,0), lookat=Vec3(0))
ERROR: type cannot be constructed
 in createwindow at /Users/solver/.julia/v0.3/GLWindow/src/reactglfw.jl:325
 in createdisplay at /Users/solver/.julia/v0.3/GLPlot/src/GLPlot.jl:51

julia> Pkg.status()
2 required packages:
 - GLPlot                        0.0.5+             master
 - Jewel                         1.0.4
37 additional packages:
 - BinDeps                       0.3.12
 - Calculus                      0.1.6
 - Color                         0.4.5
 - Compat                        0.4.4
 - Compose                       0.3.12
 - DataStructures                0.3.9
 - Datetime                      0.1.7
 - Docile                        0.5.2
 - DualNumbers                   0.1.3
 - FactCheck                     0.2.7
 - FixedPointNumbers             0.0.7
 - GLAbstraction                 0.0.5+             master
 - GLFW                          1.0.0-alpha.6
 - GLText                        0.0.4
 - GLWindow                      0.0.5+             master
 - Graphics                      0.1.0
 - Homebrew                      0.1.14
 - Images                        0.4.36
 - ImmutableArrays               0.0.7
 - Iterators                     0.1.8
 - JSON                          0.4.3
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.8.4
 - Lumberjack                    0.0.3
 - ModernGL                      0.0.5+             master
 - Mustache                      0.0.9
 - NaNMath                       0.0.2
 - Quaternions                   0.0.4
 - Reactive                      0.2.0
 - Requires                      0.1.2
 - SHA                           0.0.4
 - SIUnits                       0.0.3
 - TexExtensions                 0.0.2
 - URIParser                     0.0.5
 - UUID                          0.0.2
 - Zlib                          0.1.8

julia> versioninfo()
Julia Version 0.3.7
Commit cb9bcae (2015-03-23 21:36 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by dlfivefifty** [comment]
Actually this is really a Compat bug I think.  I'll post a Compat issue.

julia> Pkg.checkout("Compat")
INFO: Checking out Compat master...
INFO: Pulling Compat latest master...
INFO: Upgrading Calculus: v0.1.6 => v0.1.8

julia> using Compat

julia> @compat(Cint(false))
ERROR: type cannot be constructed

**Comment by SimonDanisch** [comment]
Have you tried pulling Compat master? That solved something for me at some point...

**Comment by dlfivefifty** [comment]
Yes I did

**Comment by SimonDanisch** [comment]
Hm next problem seems to be the API update of Reactive..
Pkg.pin("Reactive", v"0.1.10") seems to fix that problem!
Can you report if everything works fine for you? Then I can create some new tags for the last Julia 0.3 compatible GLPlot version ;)

**Comment by dlfivefifty** [comment]
Still no:


julia> using GLPlot,GLAbstraction

julia> createdisplay(;async=false, w=500, h=500, eyeposition=Vec3(1,1,0), lookat=Vec3(0))
ERROR: type cannot be constructed
 in createwindow at /Users/solver/.julia/v0.3/GLWindow/src/reactglfw.jl:325
 in createdisplay at /Users/solver/.julia/v0.3/GLPlot/src/GLPlot.jl:51

julia> Pkg.status()
3 required packages:
 - ApproxFun                     0.0.5+             master
 - GLPlot                        0.0.5+             master
 - Jewel                         1.0.4
37 additional packages:
 - BinDeps                       0.3.12
 - Calculus                      0.1.8
 - Color                         0.4.5
 - Compat                        0.4.4              master
 - Compose                       0.3.12
 - DataStructures                0.3.9
 - Datetime                      0.1.7
 - Docile                        0.5.2
 - DualNumbers                   0.1.3
 - FactCheck                     0.2.7
 - FixedPointNumbers             0.0.7
 - GLAbstraction                 0.0.5+             master
 - GLFW                          1.0.0-alpha.6
 - GLText                        0.0.4
 - GLWindow                      0.0.5+             master
 - Graphics                      0.1.0
 - Homebrew                      0.1.14
 - Images                        0.4.36
 - ImmutableArrays               0.0.7
 - Iterators                     0.1.8
 - JSON                          0.4.3
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.8.4
 - Lumberjack                    0.0.3
 - ModernGL                      0.0.5+             master
 - Mustache                      0.0.9
 - NaNMath                       0.0.2
 - Quaternions                   0.0.4
 - Reactive                      0.1.10             pinned.f8f5208f.tmp
 - Requires                      0.1.2
 - SHA                           0.0.4
 - SIUnits                       0.0.3
 - TexExtensions                 0.0.2
 - URIParser                     0.0.5
 - UUID                          0.0.2
 - Zlib                          0.1.8

**Comment by SimonDanisch** [comment]
Sorry I haven't be very clear... This fixes the error that turns up after fixing line 325 in reactglfw.jl.
I'll push a short fix to GLWindow.

**Comment by dlfivefifty** [comment]
OK That fixed the creating window bug.  I’ll now make sure all my examples still work.

**Comment by SimonDanisch** [comment]
Great! If you can publish them afterwards I can see if they also work with GLVisualize (if you're not interested in doing this yourself).

**Comment by dlfivefifty** [comment]
All the examples work!
