### ISSUE TITLE
Color is deprecated, please switch to Colors (tagged version issue?)

### ISSUE THREAD

**Issue by timholy** [SimonDanisch/GLPlot.jl#30]
See https://github.com/JuliaLang/METADATA.jl/pull/3769; we're about to make Color uninstallable on julia 0.4.

Transition info is [here](https://github.com/JuliaGraphics/Colors.jl#migrating-from-colorjl).

**Comment by SimonDanisch** [comment]
Thanks, but `GLPlot` on master is already on Colors ;)

**Comment by timholy** [comment]
Can you tag a new version, then? See https://github.com/JuliaLang/METADATA.jl/pull/3769.

**Comment by SimonDanisch** [comment]
It should be okay as it is. The new GLPlot is not ready for a new tag (hopefully in a few days it will) and the old one is in a broken state anyways... No one has complained yet, so I guess it will also be fine for the next days :D

**Comment by timholy** [comment]
Works for me, and now you've given me a citation :smile:.
