### ISSUE TITLE
Is GLVisualize or GLPlot working for anyone?

### ISSUE THREAD

**Issue by juliohm** [SimonDanisch/GLPlot.jl#45]
I am consistently trying to use GLVisualize.jl in my research, either via Plots.jl or via GLPlot.jl. Every time I give the packages a try, I get a set of syntax errors, e.g. missing ")", inconsistent dependencies, etc.

I tried both stable releases and the master branch, all are broken on my machine. Can you share a working combination of versions if it exists?

**Comment by hustf** [comment]
Julio, I share some of the same experience and really look forward to when this great effort brings consistently stable versions on all platforms. 

The next best contribution we can make in the meantime is being precise in giving feedback. Your julia version, hardware, error logs? Then, if we do have success, share a link to examples with precise version info on our own repos?

**Comment by juliohm** [comment]
@hustf I am using all the current stable versions of Julia and packages as I did a long time ago with older releases of Julia. I can give more details below, but I don't think this is an issue that is affecting only my machine.

```julia
julia> versioninfo()
Julia Version 0.6.1-pre.0
Commit dcf39a1dda* (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
julia> Pkg.status("GLVisualize")
 - GLVisualize                   0.2.2
julia> Pkg.status("GLPlot")
 - GLPlot                        0.0.4
# have also tried with master
julia> Pkg.status("GLPlot")
 - GLPlot                        0.0.5+ master
```

There is definitely an urgent need for something stable, specially given the first official major release of Julia coming out.

**Comment by SimonDanisch** [comment]
Sorry, GLPlot isn't that well maintained, since I still don't have a good UI story going for it.
Is GLVisualize working for you?

**Comment by juliohm** [comment]
@SimonDanisch I didn't have the chance to try GLVisualize directly, my only attempts were through GLPlot.jl and Plots.jl.

**Comment by loicspace** [comment]
I have been using GLVisualize extensively on Julia 0.5 and it has been working wonderfully for me, both on Windows 10 and Ubuntu 16.04, directly though not through GLPlot or Plots. I'm not having much success with GLPlot yet.
I did have some issues with my graphics card and had to install Nvidia proprietary drivers and enable the GPU -- in case you get an error of the like "Intel flush lock" something.

**Comment by SimonDanisch** [comment]
Great! Btw, Plots.jl should be fixed with the GLVisualize backend...
GLPlot it not currently maintained.. I need to figure out in which direction I want to evolve things first ;)

**Comment by juliohm** [comment]
I am closing this issue for now. Plots.jl is working again.
